services:
  # Frontend service
  front-end:
    build:
      context: ./front-end
    ports:
      - "80:80"
    depends_on:
      - proxy

  # Backend service (API)
  back-end:
    build:
      context: ./back-end
    environment:
      - FLASK_APP=api.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5252
    expose:
      - "5252"

  # Proxy service (Nginx as load balancer)
  proxy:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - back-end
